---  Drop Tables

DROP TABLE iw_interadm CASCADE CONSTRAINTS;
DROP TABLE iw_interuser CASCADE CONSTRAINTS;
DROP TABLE iw_passoideal CASCADE CONSTRAINTS;
DROP TABLE iw_passoreal CASCADE CONSTRAINTS;
DROP TABLE iw_processoideal CASCADE CONSTRAINTS;
DROP TABLE iw_processoreal CASCADE CONSTRAINTS;
DROP TABLE iw_usuario CASCADE CONSTRAINTS;

DROP SEQUENCE iw_processoideal_seq;
DROP SEQUENCE iw_processoreal_seq;
DROP SEQUENCE iw_interadm_seq;
DROP SEQUENCE iw_interuser_seq;
DROP SEQUENCE iw_passoideal_seq;
DROP SEQUENCE iw_passoreal_seq;
DROP SEQUENCE iw_usuario_seq;

-- Cria��o das Tabelas

-- Tabela iw_interadm
CREATE TABLE iw_interadm (
    interadmid        NUMBER(30) NOT NULL,
    url               VARCHAR2(255) NOT NULL,
    local_clique      VARCHAR2(255) NOT NULL,
    tipo_clique       VARCHAR2(255) NOT NULL,
    tempo_real        INTERVAL DAY(9) TO SECOND(0) NOT NULL,
    timestamp         TIMESTAMP NOT NULL,
    iw_usuario_userid NUMBER(30) NOT NULL,
    CONSTRAINT iw_interadm_pk PRIMARY KEY (interadmid)
);

-- Tabela iw_interuser
CREATE TABLE iw_interuser (
    interuserid       NUMBER(30) NOT NULL,
    url               VARCHAR2(255) NOT NULL,
    local_clique      VARCHAR2(255) NOT NULL,
    tipo_clique       VARCHAR2(255) NOT NULL,
    tempo_real        INTERVAL DAY(9) TO SECOND(0) NOT NULL,
    timestamp         TIMESTAMP NOT NULL,
    iw_usuario_userid NUMBER(30) NOT NULL,
    CONSTRAINT iw_interuser_pk PRIMARY KEY (interuserid)
);

-- Tabela iw_passoideal
CREATE TABLE iw_passoideal (
    passoidealid                  NUMBER(30) NOT NULL,
    local_clique                  VARCHAR2(255) NOT NULL,
    tipo_clique                   VARCHAR2(255) NOT NULL,
    tempo_estimado                INTERVAL DAY(9) TO SECOND(0) NOT NULL,
    iw_processoideal_proceidealid NUMBER(30) NOT NULL,
    CONSTRAINT iw_passoideal_pk PRIMARY KEY (passoidealid)
);

-- Tabela iw_passoreal
CREATE TABLE iw_passoreal (
    passorealid                    NUMBER(30) NOT NULL,
    local_clique                   VARCHAR2(255) NOT NULL,
    tipo_clique                    VARCHAR2(255) NOT NULL,
    tempo_real                     INTERVAL DAY(9) TO SECOND(0) NOT NULL,
    iw_processoreal_processorealid NUMBER(30) NOT NULL,
    CONSTRAINT iw_passoreal_pk PRIMARY KEY (passorealid)
);

-- Tabela iw_processoideal
CREATE TABLE iw_processoideal (
    proceidealid           NUMBER(30) NOT NULL,
    nome_processo          VARCHAR2(255) NOT NULL,
    url_inicio             VARCHAR2(255) NOT NULL,
    clique_inicio          VARCHAR2(255) NOT NULL,
    url_fim                VARCHAR2(255),
    clique_fim             VARCHAR2(255),
    tempo_real             INTERVAL DAY(9) TO SECOND(0) NOT NULL,
    iw_usuario_userid      NUMBER(30) NOT NULL,
    iw_interadm_interadmid NUMBER(30) NOT NULL,
    CONSTRAINT iw_processoideal_pk PRIMARY KEY (proceidealid)
);

-- Tabela iw_processoreal
CREATE TABLE iw_processoreal (
    procerealid                   NUMBER(30) NOT NULL,
    nome_processo                 VARCHAR2(255) NOT NULL,
    url_inicio                    VARCHAR2(255) NOT NULL,
    clique_inicio                 VARCHAR2(100) NOT NULL,
    url_fim                       VARCHAR2(255) NOT NULL,
    clique_fim                    VARCHAR2(255) NOT NULL,
    percentual_aceitacao          NUMBER(5, 2) NOT NULL,
    resultado                     VARCHAR2(255) NOT NULL,
    timestamp                     TIMESTAMP NOT NULL,
    iw_processoideal_proceidealid NUMBER(30) NOT NULL,
    iw_interuser_interuserid      NUMBER(30) NOT NULL,
    CONSTRAINT iw_processoreal_pk PRIMARY KEY (procerealid)
);

-- Tabela iw_usuario
CREATE TABLE iw_usuario (
    userid NUMBER(30) NOT NULL,
    CONSTRAINT iw_usuario_pk PRIMARY KEY (userid)
);

-- Tabela INSIGHTS
CREATE TABLE INSIGHTS (
    ID_INSIGHT NUMBER GENERATED BY DEFAULT AS IDENTITY,
    STEP VARCHAR2(100),
    DURATION_SECONDS NUMBER,
    CLICKS NUMBER,
    REFERENCE_DURATION_SECONDS NUMBER,
    REFERENCE_CLICKS NUMBER,
    INSIGHT_TEXT CLOB,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_INSIGHT)
)

-- Cria��o das Sequ�ncias

-- Sequ�ncia para iw_processoideal
CREATE SEQUENCE iw_processoideal_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_processoreal
CREATE SEQUENCE iw_processoreal_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_interadm
CREATE SEQUENCE iw_interadm_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_interuser
CREATE SEQUENCE iw_interuser_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_passoideal
CREATE SEQUENCE iw_passoideal_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_passoreal
CREATE SEQUENCE iw_passoreal_seq START WITH 1 INCREMENT BY 1;

-- Sequ�ncia para iw_usuario (se precisar de auto-incremento)
CREATE SEQUENCE iw_usuario_seq START WITH 1 INCREMENT BY 1;


-- Adicionar Chaves Estrangeiras

ALTER TABLE iw_interadm
    ADD CONSTRAINT iw_interadm_iw_usuario_fk FOREIGN KEY (iw_usuario_userid)
    REFERENCES iw_usuario(userid);

ALTER TABLE iw_interuser
    ADD CONSTRAINT iw_interuser_iw_usuario_fk FOREIGN KEY (iw_usuario_userid)
    REFERENCES iw_usuario(userid);

ALTER TABLE iw_passoideal
    ADD CONSTRAINT fk_passoideal_proceideal FOREIGN KEY (iw_processoideal_proceidealid)
    REFERENCES iw_processoideal(proceidealid);

ALTER TABLE iw_passoreal
    ADD CONSTRAINT fk_passoreal_processoreal FOREIGN KEY (iw_processoreal_processorealid)
    REFERENCES iw_processoreal(procerealid);

ALTER TABLE iw_processoideal
    ADD CONSTRAINT fk_proceideal_interadm FOREIGN KEY (iw_interadm_interadmid)
    REFERENCES iw_interadm(interadmid);

ALTER TABLE iw_processoideal
    ADD CONSTRAINT fk_proceideal_usuario FOREIGN KEY (iw_usuario_userid)
    REFERENCES iw_usuario(userid);

ALTER TABLE iw_processoreal
    ADD CONSTRAINT fk_processoreal_interuser FOREIGN KEY (iw_interuser_interuserid)
    REFERENCES iw_interuser(interuserid);

ALTER TABLE iw_processoreal
    ADD CONSTRAINT fk_processoreal_proceideal FOREIGN KEY (iw_processoideal_proceidealid)
    REFERENCES iw_processoideal(proceidealid);



-- Inserir usu�rios

-- Inserir usu�rio comum
INSERT INTO iw_usuario (userid)
VALUES (iw_usuario_seq.NEXTVAL);

-- Inserir um administrador
INSERT INTO iw_usuario (userid)
VALUES (iw_usuario_seq.NEXTVAL);


select * from iw_usuario;

-- Inserir intera��es administrativas

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputNotaFiscal',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputDetalhes',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'btnConfirmar',
    'clicar',
    INTERVAL '1' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

INSERT INTO iw_interadm (
    interadmid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES
(
    iw_interadm_seq.NEXTVAL,
    'http://example.com/confirmacao-cadastro',
    'btnCancelar',
    'clicar',
    INTERVAL '1' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);


-- processo ideal
INSERT INTO iw_processoideal (
    proceidealid,
    nome_processo,
    url_inicio,
    clique_inicio,
    url_fim,
    clique_fim,
    tempo_real,
    iw_usuario_userid,
    iw_interadm_interadmid
) VALUES (
    iw_processoideal_seq.NEXTVAL, -- Gera o pr�ximo valor da sequ�ncia
    'Cadastro de Nota Fiscal', -- Nome do processo ideal
    'http://example.com/cadastro-nota-fiscal', -- URL de in�cio
    'inputEmitente', -- Elemento de in�cio
    'http://example.com/confirmacao-cadastro', -- URL de fim
    'btnConfirmar', -- Elemento de fim
    INTERVAL '15' MINUTE, -- Tempo real total estimado para o processo (ajuste conforme necess�rio)
    1, -- Substitua com um valor de usu�rio v�lido
    1  -- Substitua com um valor de intera��o administrativa v�lido
);

select * from iw_interadm;
select * from iw_processoideal;

-- Inserir passos ideais
-- Inserir o primeiro passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);

-- Inserir o segundo passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'inputNotaFiscal',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);

-- Inserir o terceiro passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'inputDetalhes',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);

-- Inserir o quarto passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'btnConfirmar',
    'clicar',
    INTERVAL '1' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);

-- Inserir o quinto passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);

-- Inserir o sexto passo ideal
INSERT INTO iw_passoideal (
    passoidealid,
    local_clique,
    tipo_clique,
    tempo_estimado,
    iw_processoideal_proceidealid
) VALUES (
    iw_passoideal_seq.NEXTVAL,
    'btnCancelar',
    'clicar',
    INTERVAL '1' MINUTE,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal')
);



desc iw_interuser;

-- Inserir intera��es de usu�rio
-- Inserir o primeiro registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o segundo registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputNotaFiscal',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o terceiro registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputDetalhes',
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o quarto registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'inputOutroCampo',  -- Adicionando uma intera��o entre a primeira e a �ltima
    'preencher',
    INTERVAL '2' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o quinto registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/cadastro-nota-fiscal',
    'btnConfirmar',
    'clicar',
    INTERVAL '1' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o sexto registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/confirmacao-cadastro',
    'btnConfirmar',
    'clicar',
    INTERVAL '1' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);

-- Inserir o s�timo registro
INSERT INTO iw_interuser (
    interuserid,
    url,
    local_clique,
    tipo_clique,
    tempo_real,
    timestamp,
    iw_usuario_userid
) VALUES (
    iw_interuser_seq.NEXTVAL,
    'http://example.com/confirmacao-cadastro',
    'btnCancelar',
    'clicar',
    INTERVAL '1' MINUTE,
    CURRENT_TIMESTAMP,
    (SELECT userid FROM iw_usuario WHERE ROWNUM = 1)
);


SELECT userid FROM iw_usuario WHERE ROWNUM = 1;
select * from iw_usuario;
select * from iw_interuser;


-- Inserir um processo real
INSERT INTO iw_processoreal (
    procerealid,
    nome_processo,
    url_inicio,
    clique_inicio,
    url_fim,
    clique_fim,
    percentual_aceitacao,
    resultado,
    timestamp,
    iw_processoideal_proceidealid,
    iw_interuser_interuserid
) VALUES (
    iw_processoreal_seq.NEXTVAL,
    'Cadastro de Nota Fiscal',
    'http://example.com/cadastro-nota-fiscal',
    'inputEmitente',
    'http://example.com/confirmacao-cadastro',
    'btnCancelar',
    90.00, -- Percentual de aceita��o fict�cio
    'Conclu�do',
    CURRENT_TIMESTAMP,
    (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal'),
    (SELECT interuserid FROM iw_interuser WHERE ROWNUM = 1) 
);

SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal';
select * from iw_processoreal;
select * from iw_processoideal;

-- Inserir passos reais
-- Inser��o 1
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'inputEmitente',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 2
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'inputNotaFiscal',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 3
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'inputDetalhes',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 4
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'inputOutroCampo',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 5
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'inputValidacao',
    'preencher',
    INTERVAL '2' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 6
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'btnConfirmar',
    'clicar',
    INTERVAL '1' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

-- Inser��o 7 
INSERT INTO iw_passoreal (
    passorealid,
    local_clique,
    tipo_clique,
    tempo_real,
    iw_processoreal_processorealid
) VALUES (
    iw_passoreal_seq.NEXTVAL,
    'btnCancelar',
    'clicar',
    INTERVAL '1' MINUTE,
    (SELECT procerealid FROM iw_processoreal WHERE iw_processoideal_proceidealid = 
        (SELECT proceidealid FROM iw_processoideal WHERE nome_processo = 'Cadastro de Nota Fiscal' AND ROWNUM = 1))
);

select * from iw_usuario;
select * from iw_interuser;
select * from iw_interadm;
select * from iw_processoideal;
select * from iw_passoideal;
select * from iw_processoreal;
select * from iw_passoreal;

commit;
